### ISSUE TITLE
Publish provider to HashiCorp Terraform Registry

### ISSUE THREAD

**Issue by FRosner** [codecentric/terraform-provider-leanix#12]
# Problem 

With newer Terraform versions the custom plugin integration works differently:
It will now check ~/.terraform.d/plugins/${name}/${version}/${os}_${arch} or %APPDATA%\terraform.d\plugins\${name}\${version}\${os}_${arch} (Windows).
This seems a little cumbersome to me. It might be better to publish the provider to the HashiCorp Terraform Registry , which seems easy enough: https://www.terraform.io/docs/registry/providers/publishing.html

# ToDo

- [ ] [Document Provider](https://www.terraform.io/docs/registry/providers/publishing.html#documenting-your-provider)
- [x] Tag with `vx.z.y`
- [ ] [Switch to github actions](https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-)
  - [x] Update CI pipeline to publish GitHub releases
  - [ ] Add GPG public key to organization (codecentric) namespace in Terraform Provider Registry. Apparently this needs an admin.
